In [1]:
import numpy as np

a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[9,8,7],[6,5,4]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr2

array([[9, 8, 7],
       [6, 5, 4]])

In [5]:
c=np.hstack([arr1,arr2])
c

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

In [6]:
d=np.vstack([arr1,arr2])
d

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [7]:
e=np.arange(2,21,2)
e

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
thir=np.arange(13,131,13)
thir

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [10]:
l=np.linspace(1.0,5.0,num=10)
l

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

ind=np.array([[1,2,3],[4,5,6]])
ind[0:1]

In [13]:
ind[1:2]

array([[4, 5, 6]])

In [24]:
ind[:,2]

array([3, 6])

In [27]:
ind[0:1,2]

array([3])

In [30]:
one=np.ones((4,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
arr=np.array([1,2,3,4,5])
arr += 5
arr

array([ 6,  7,  8,  9, 10])

In [32]:
arr -=2
arr

array([4, 5, 6, 7, 8])

In [39]:
arr = np.random.randint(0,10,size=[3,3])
print(arr)
print(arr.min())
print(arr.max())

[[5 5 1]
 [9 2 4]
 [7 4 7]]
1
9


In [40]:
arr = np.random.randint(0,10,size=[3,3])
print(arr)
print(arr.shape)
print("After Reshape")
print(arr.reshape(9,1))

[[4 8 4]
 [7 2 7]
 [1 3 8]]
(3, 3)
After Reshape
[[4]
 [8]
 [4]
 [7]
 [2]
 [7]
 [1]
 [3]
 [8]]


In [42]:
arr = np.random.randint(0,10,size=[3,3])
print(arr)
print(arr.shape)
print("After Reshape")
print(arr.reshape(1,9))

[[0 6 9]
 [9 4 4]
 [9 3 4]]
(3, 3)
After Reshape
[[0 6 9 9 4 4 9 3 4]]


In [43]:
one=np.ones((4,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
one[0:1]

array([[1., 1., 1., 1.]])

In [45]:
one[1:2]

array([[1., 1., 1., 1.]])

In [46]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.add(a,b)
c

array([5, 7, 9])

In [47]:
zero=np.zeros((5,2))
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
one=np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
arr=np.array([[1,2,3],[4,5,6]])
arr
arr = arr.T
print(arr)

[[1 4]
 [2 5]
 [3 6]]
