In [1]:
print("Hello World")

Hello World


In [2]:
a=[1,2,3,4]

In [4]:
print(a)

[1, 2, 3, 4]


In [6]:
import numpy as np

In [8]:
a=np.array(a)

In [9]:
print(a)

[1 2 3 4]


In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
b=[5,6,7,8]

In [12]:
c=np.array(a,b)

TypeError: Field elements must be 2- or 3-tuples, got '5'

In [13]:
 c=np.array(ab)

NameError: name 'ab' is not defined

In [14]:
c=np.array([a, b])

In [15]:
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
d=[9,8,7,6]

In [19]:
c=np.array([a,b,d])
print(c)
c.ndim

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]


2

In [21]:
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(e)
print(e.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [25]:
f = np.array([[[[[[1,2,3]],[[4,5,6]],[[7,8,9]]]]]])
print(f)
f.ndim

[[[[[[1 2 3]]

    [[4 5 6]]

    [[7 8 9]]]]]]


6

In [29]:
b=np.array([1,2,3])

In [30]:
b.size

3

In [31]:
b.shape

(3,)

In [32]:
b.itemsize

4

In [33]:
b.dtype

dtype('int32')

In [34]:
b.data

In [37]:
arr=np.array([[1,2,3],[5,6,7,8],[11,23,45,67]])
print(arr)

[list([1, 2, 3]) list([5, 6, 7, 8]) list([11, 23, 45, 67])]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5588\1898140378.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr=np.array([[1,2,3],[5,6,7,8],[11,23,45,67]])


In [38]:
arr.size
arr.shape
arr.itemsize
arr.data
arr.dtype

dtype('O')

In [39]:
arr.size

3

In [40]:
arr.shape

(3,)

In [41]:
arr.itemsize

8

In [42]:
arr.data

In [44]:
arr.min()

[1, 2, 3]

In [45]:
bc=np.array([11,24,56,78,21,8,45])

In [46]:
bc.min()

8

In [47]:
bc.max()

78

In [48]:
bc.sum()

243

In [49]:
np.log(bc)

array([2.39789527, 3.17805383, 4.02535169, 4.35670883, 3.04452244,
       2.07944154, 3.80666249])

In [50]:
bc.multiply()

AttributeError: 'numpy.ndarray' object has no attribute 'multiply'

In [51]:
sam=np.array([[5,6,7],[1,2,3]])
np.multiply(sam)

TypeError: multiply() takes from 2 to 3 positional arguments but 1 were given

In [53]:
ab=np.array([1,2,3])
ac=np.array([5,6,7])
ad = np.multiply(ab,ac)

In [54]:
print(ad)

[ 5 12 21]


In [55]:
print(np.add(ab,ac))

[ 6  8 10]


In [56]:
print(np.power(ab,ac))

[   1   64 2187]


In [2]:
ar=np.array([1,2,3])
print(ar)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [15]:
arr=np.array([1,23,4,11,8,6])
print(arr)

[ 1 23  4 11  8  6]


In [16]:
brr=np.copy(arr)
print(brr)

[ 1 23  4 11  8  6]


In [17]:
arr.view(dtype='float32')

array([1.4e-45, 3.2e-44, 5.6e-45, 1.5e-44, 1.1e-44, 8.4e-45],
      dtype=float32)

In [19]:
arr.sort()

In [21]:
print(arr)

[ 1  4  6  8 11 23]


In [24]:
crr=np.array([[3,2,1],[4,6,5]])

In [27]:
a=crr.reshape(1,6)
print(a)

[[3 2 1 4 6 5]]


In [31]:
a=crr.reshape(6,1)
print(a)

[[3]
 [2]
 [1]
 [4]
 [6]
 [5]]


In [35]:
drr=np.append(arr,[9,8,7])
print(drr)

[list([3, 2, 1]) list([4, 6, 5, 2]) 9 8 7]


In [37]:
print(crr)

[[3 2 1]
 [4 6 5]]


In [38]:
a=np.array([1,2,3,8,5])
b=np.insert(a,3,85)
print(b)

[ 1  2  3 85  8  5]


In [39]:
np.insert(a,2,20)
print(a)

[1 2 3 8 5]


In [40]:
c=np.delete(a,2,axis=0)
print(c)

[1 2 8 5]


In [45]:
d=np.delete(a,2,axis=1)
print(d)

AxisError: axis 1 is out of bounds for array of dimension 1

In [50]:
arr1=np.array([12,2,4,5])
arr2=np.array([9,8,7])
p=np.concatenate((arr1,arr2),axis=0)
print(p)

AxisError: axis 1 is out of bounds for array of dimension 1

In [54]:
arr3=np.array([[12,2,4,5],[50,40,30,10]])
arr4=np.array([[9,8,7,1],[10,20,30,20]])
p=np.concatenate((arr3,arr4),axis=1)
print(p)

[[12  2  4  5  9  8  7  1]
 [50 40 30 10 10 20 30 20]]


In [59]:
print(arr1)
s=np.split(arr1,2)
print(s)

[12  2  4  5]
[array([12,  2]), array([4, 5])]


In [61]:
s=arr1[1]
print(s)

2


In [68]:
s=arr1[1:3]=1
print(s)
print(arr1)

1
[12  1  1  5]


In [71]:
print(arr3)
s=arr3[0,3]
print(s)

[[12  2  4  5]
 [50 40 30 10]]
5


In [75]:
print(arr1)
arr1[0:3]

[12  1  1  5]


array([12,  1,  1])

In [79]:
arr1[0:3:2]

array([12,  1])

In [81]:
print(arr1,arr2)

[12  1  1  5] [9 8 7]


In [2]:
import numpy as np
arr1=np.array([12,2,4])
arr2=np.array([9,8,7])
add=np.add(arr1,arr2)
print(add)

[21 10 11]


In [3]:
sub=np.subtract(arr1,arr2)
print(sub)

[ 3 -6 -3]


In [4]:
mul=np.multiply(arr1,arr2)
print(mul)

[108  16  28]


In [5]:
div=np.divide(arr1,arr2)
print(div)

[1.33333333 0.25       0.57142857]


In [6]:
exp=np.exp(arr1)
print(exp)

[1.62754791e+05 7.38905610e+00 5.45981500e+01]


In [7]:
sqr=np.sqrt(arr1)
print(sqr)

[3.46410162 1.41421356 2.        ]


In [8]:
com=np.array_equal(arr1,arr2)
print(com)

False


In [12]:
arr=np.array([[1,2,3],[4,5,6]])
s=arr.sum()
s

21

In [13]:
arr.min()

1

In [15]:
arr.max()

6

In [16]:
arr.mean()

3.5

In [17]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [18]:
med=np.median(arr)
med

3.5